// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.fok.core.db.bdb.model;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SecondaryValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.fok.core.db.bdb.model.SecondaryValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes secondaryKey = 2;</code>
     */
    com.google.protobuf.ByteString getSecondaryKey();
  }
  /**
   * Protobuf type {@code org.fok.core.db.bdb.model.SecondaryValue}
   */
  public  static final class SecondaryValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.fok.core.db.bdb.model.SecondaryValue)
      SecondaryValueOrBuilder {
    // Use SecondaryValue.newBuilder() to construct.
    private SecondaryValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecondaryValue() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      secondaryKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SecondaryValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 18: {

              secondaryKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fok.core.db.bdb.model.Entity.internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fok.core.db.bdb.model.Entity.internal_static_org_fok_core_db_bdb_model_SecondaryValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fok.core.db.bdb.model.Entity.SecondaryValue.class, org.fok.core.db.bdb.model.Entity.SecondaryValue.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int SECONDARYKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString secondaryKey_;
    /**
     * <code>bytes secondaryKey = 2;</code>
     */
    public com.google.protobuf.ByteString getSecondaryKey() {
      return secondaryKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!secondaryKey_.isEmpty()) {
        output.writeBytes(2, secondaryKey_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!secondaryKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, secondaryKey_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.fok.core.db.bdb.model.Entity.SecondaryValue)) {
        return super.equals(obj);
      }
      org.fok.core.db.bdb.model.Entity.SecondaryValue other = (org.fok.core.db.bdb.model.Entity.SecondaryValue) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getSecondaryKey()
          .equals(other.getSecondaryKey());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + SECONDARYKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSecondaryKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fok.core.db.bdb.model.Entity.SecondaryValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.fok.core.db.bdb.model.Entity.SecondaryValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.fok.core.db.bdb.model.SecondaryValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.fok.core.db.bdb.model.SecondaryValue)
        org.fok.core.db.bdb.model.Entity.SecondaryValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fok.core.db.bdb.model.Entity.internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fok.core.db.bdb.model.Entity.internal_static_org_fok_core_db_bdb_model_SecondaryValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.fok.core.db.bdb.model.Entity.SecondaryValue.class, org.fok.core.db.bdb.model.Entity.SecondaryValue.Builder.class);
      }

      // Construct using org.fok.core.db.bdb.model.Entity.SecondaryValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        secondaryKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.fok.core.db.bdb.model.Entity.internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor;
      }

      public org.fok.core.db.bdb.model.Entity.SecondaryValue getDefaultInstanceForType() {
        return org.fok.core.db.bdb.model.Entity.SecondaryValue.getDefaultInstance();
      }

      public org.fok.core.db.bdb.model.Entity.SecondaryValue build() {
        org.fok.core.db.bdb.model.Entity.SecondaryValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.fok.core.db.bdb.model.Entity.SecondaryValue buildPartial() {
        org.fok.core.db.bdb.model.Entity.SecondaryValue result = new org.fok.core.db.bdb.model.Entity.SecondaryValue(this);
        result.data_ = data_;
        result.secondaryKey_ = secondaryKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.fok.core.db.bdb.model.Entity.SecondaryValue) {
          return mergeFrom((org.fok.core.db.bdb.model.Entity.SecondaryValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.fok.core.db.bdb.model.Entity.SecondaryValue other) {
        if (other == org.fok.core.db.bdb.model.Entity.SecondaryValue.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getSecondaryKey() != com.google.protobuf.ByteString.EMPTY) {
          setSecondaryKey(other.getSecondaryKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.fok.core.db.bdb.model.Entity.SecondaryValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.fok.core.db.bdb.model.Entity.SecondaryValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString secondaryKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes secondaryKey = 2;</code>
       */
      public com.google.protobuf.ByteString getSecondaryKey() {
        return secondaryKey_;
      }
      /**
       * <code>bytes secondaryKey = 2;</code>
       */
      public Builder setSecondaryKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secondaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes secondaryKey = 2;</code>
       */
      public Builder clearSecondaryKey() {
        
        secondaryKey_ = getDefaultInstance().getSecondaryKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.fok.core.db.bdb.model.SecondaryValue)
    }

    // @@protoc_insertion_point(class_scope:org.fok.core.db.bdb.model.SecondaryValue)
    private static final org.fok.core.db.bdb.model.Entity.SecondaryValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.fok.core.db.bdb.model.Entity.SecondaryValue();
    }

    public static org.fok.core.db.bdb.model.Entity.SecondaryValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecondaryValue>
        PARSER = new com.google.protobuf.AbstractParser<SecondaryValue>() {
      public SecondaryValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SecondaryValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SecondaryValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SecondaryValue> getParserForType() {
      return PARSER;
    }

    public org.fok.core.db.bdb.model.Entity.SecondaryValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fok_core_db_bdb_model_SecondaryValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014entity.proto\022\031org.fok.core.db.bdb.mode" +
      "l\"4\n\016SecondaryValue\022\014\n\004data\030\001 \001(\014\022\024\n\014sec" +
      "ondaryKey\030\002 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_fok_core_db_bdb_model_SecondaryValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fok_core_db_bdb_model_SecondaryValue_descriptor,
        new java.lang.String[] { "Data", "SecondaryKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
